### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Dzoge** [malloyca/realstretch#41]
Nice plugin ❤️ 

The released VST and Audiounit plugins don't seem to work on M1 macs.

Could you release the version of these plugins supporting Apple Sillicon chips please?
Or maybe share the source code building instructions to build them locally?

**Comment by Dzoge** [comment]
Sorry, false alarm.

**Comment by malloyca** [comment]
Thanks for checking out the plugin.

Were you able to build it or are you running the compiled versions under Rosetta? I don't have an M1 Mac to compile new versions on yet, but will post them once I can.

There are some updates I want to do on this project anyway, so hopefully I'll get all of this taken care of soon.
